export enum ImageType {
  NO_IMAGE_DATA = 0,
  COLOR_MAPPED = 1,
  TRUE_COLOR = 2,
  GRAY_SCALE = 3,
  RUN_LENGTH_ENCODED_COLOR_MAPPED = 9,
  RUN_LENGTH_ENCODED_TRUE_COLOR = 10,
  RUN_LENGTH_ENCODED_GRAY_SCALE = 11,
}

export enum ImageDescriptorFields {
export enum AttributesType {
  NO_ALPHA_DATA = 0,
  UNDEFINED_IGNORED = 1,
  UNDEFINED_RETAINED = 2,
  USEFUL_ALPHA_CHANNEL = 3,
  PREMULTIPLIED_ALPHA = 4,
}
